[package]
name = "muhex"
version = "0.0.1"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.5.1"
hex = "0.4.3"
proptest = "1.6.0"
test-strategy = "0.4.0"

[[bench]]
name = "benchmark"
harness = false
